name: CK Metrics

on:
  push:
    branches: [ main ]

jobs:
  ck:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Download CK
        run: mvn dependency:get -Dartifact=com.github.mauricioaniche:ck:0.7.0

      - name: Run CK
        run: |
          java -jar ~/.m2/repository/com/github/mauricioaniche/ck/0.7.1/ck-0.7.1-jar-with-dependencies.jar \
          src/main/java false 0 false ck-output

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: ck-metrics
          path: ck-output
